controller_frequency: 20

TrajectoryPlannerROS:
  max_vel_x: 0.5 #0.5
  min_vel_x: 0.1 #  didn't realize this is miniimum forward velocity, not backwards velocity. see here https://wiki.ros.org/base_local_planner#Parameters
  max_vel_theta: 1.0 #1.5

  min_in_place_vel_theta: 0.1

  acc_lim_theta: 1.0
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  sim_time: 2.0 # The amount of time to forward-simulate trajectories in seconds https://wiki.ros.org/base_local_planner#Parameters

  vx_samples: 12.0
  vtheta_samples: 20.0


  pdist_scale: 0.1 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.60

  holonomic_robot: false

  # this is in an attempt to get the robot to stop spinning in circles in place when it reaches the destination
  xy_goal_tolerance: 0.2        
  yaw_goal_tolerance: 0.2 

  # once reached the x,y coordinates, only spin in place to fix orientation (regardless of whether this causes the robot to drif)
  latch_xy_goal_tolerance: true